# Generated by Django 4.2.27 on 2025-12-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("level", models.CharField(max_length=20)),
                ("logger_name", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("test_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
